Fix the issue related google_service.json file not found

diff --git a/.github/workflows/manual_deploy_to_firebase.yml b/.github/workflows/manual_deploy_to_firebase.yml
--- a/.github/workflows/manual_deploy_to_firebase.yml
+++ b/.github/workflows/manual_deploy_to_firebase.yml
@@ -14,21 +14,32 @@ jobs:
     name: Building and distributing app
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-      - uses: actions/setup-java@v3
+      - uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
-          java-version: '17'
+          java-version: '21'
 
       - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/actions/setup-gradle@v4
 
       - name: Make gradlew executable
         run: chmod +x ./gradlew
 
-      - name: Execute Gradle command - assembleDebug
-        run: ./gradlew assembleDebug
+      - name: Create google-services.json
+        env:
+          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
+        run: |
+          if [ -z "$GOOGLE_SERVICES_JSON" ]; then
+            echo "Error: GOOGLE_SERVICES_JSON secret is empty or not set."
+            exit 1
+          fi
+          echo "$GOOGLE_SERVICES_JSON" > composeApp/google-services.json
+          ls -l composeApp/google-services.json
+
+      - name: Execute Gradle command - assembleQaDebug
+        run: ./gradlew :composeApp:assembleQaDebug
 
       - name: Upload Artifact to Firebase App Distribution
         uses: wzieba/Firebase-Distribution-Github-Action@v1
@@ -36,5 +47,5 @@ jobs:
           appId: ${{ secrets.FIREBASE_APP_ID }}
           serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
           groups: testers
-          file: app/build/outputs/apk/debug/app-debug.apk
+          file: composeApp/build/outputs/apk/qa/debug/composeApp-qa-debug.apk
           releaseNotes: ${{ inputs.release_notes }}
